### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by garrett-cn** [sunshineatnoon/LinearStyleTransfer#1]
### An error occurred when I ran the SPN.py file in the libs folder. Error is as follows:
torch.Size([1, 3, 256, 256])
torch.Size([1, 3, 256, 256])
torch.Size([1, 3, 256, 256])
torch.Size([1, 3, 256, 256])
torch.Size([1, 3, 256, 256])
torch.Size([1, 3, 256, 256])
torch.Size([1, 3, 256, 256])
torch.Size([1, 3, 256, 256])
torch.Size([1, 3, 256, 256])
torch.Size([1, 3, 256, 256])
torch.Size([1, 3, 256, 256])
torch.Size([1, 3, 256, 256])
torch.Size([1, 3, 256, 256])
torch.Size([1, 3, 256, 256])
torch.Size([1, 3, 256, 256])
torch.Size([1, 3, 256, 256])
torch.Size([1, 3, 256, 256])
torch.Size([1, 3, 256, 256])
torch.Size([1, 3, 256, 256])
torch.Size([1, 3, 256, 256])
Traceback (most recent call last):
  File "SPN.py", line 155, in <module>
    output = spn(x,rgb)
  File "/home/cgl/miniconda3/envs/SPN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "SPN.py", line 138, in forward
    out1 = self.left_right(X,G[0],G[1],G[2])
  File "/home/cgl/miniconda3/envs/SPN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "SPN.py", line 17, in forward
    sum_abs = G1.abs() + G2.abs() + G3.abs()
RuntimeError: CUDA error: out of memory

**Comment by garrett-cn** [comment]
Environment：CUDA8.0, pytorch-0.4.0

**Comment by garrett-cn** [comment]
Enviroment: CUDA-8.0, pytorch-0.4.1, python-3.6

**Comment by sunshineatnoon** [comment]
Hi, what command did you run? I tried to run `python TestPhotoReal.py` under the following environment, it runs fine.

```
torch==0.4.1
CUDA 8.0
python 3.6.0
```

**Comment by sunshineatnoon** [comment]
Close for now, feel free to reopen if the issue still exists.
