### ISSUE TITLE
code about encoder and decoder pretrain

### ISSUE THREAD

**Issue by lynlynlyn96** [sunshineatnoon/LinearStyleTransfer#11]
Hi
    I had read your paper "Learning Linear Transformations for Fast Image and Video Style Transfer".   And it was a great inspiration to me.
    Now I want to use encoder and decoder module pretrained in my own dataset. I hope you can provide the code of the pretraining process. It will be very helpful to me. Thank you for taking the time.

**Comment by sunshineatnoon** [comment]
We use the pre-trained encoder and decoder from the [WCT](https://arxiv.org/pdf/1705.08086.pdf) paper, please reach out the authors for encoder and decoder training code.
