### ISSUE TITLE
[code] Question about the parameter

### ISSUE THREAD

**Issue by diaodeyi** [sunshineatnoon/LinearStyleTransfer#16]
The style weight and content weight in other style transfer model usually is the former is larger than latter.
But in your experiment is inverse, the former is lower than the latter , is there any reason for this, please?

**Comment by sunshineatnoon** [comment]
Different to conventional practice for the MSE loss, we didn't use average between two gram matrices as shown [here](https://github.com/sunshineatnoon/LinearStyleTransfer/blob/master/libs/Criterion.py#L16). From my experience, this gives better stylization results. This is why the style loss weight is smaller. 

As to the specific value of the style weight, it is empirically decided.
