### ISSUE TITLE
[code] Question about Vggnet

### ISSUE THREAD

**Issue by Luciferkiss** [sunshineatnoon/LinearStyleTransfer#19]
Hi, thank you for your great work!
I find that your vgg19's layers and parameters are both different from what i use  .I wanna know how you get your vgg19 and if it came from other people ,how can i get whole layer's parameters of vgg19 with the format of ".pth"? For example,your pretrained vgg19 model only has "vgg_r31.pth","vgg_r41.pth","vgg_r51.pth",and what if i want to use relu_5_2 in vggnet?
_here is part of your vggnet:_
![DUQ 7~RS0C4 Z0P) }I3 QN](https://user-images.githubusercontent.com/71599270/155669913-137f1e8d-bfe3-48e0-b903-5aacd3fb78e6.png)
here is part of my vggnet:
![NWJ0(@FQ~R16KF93E27BMZB](https://user-images.githubusercontent.com/71599270/155669961-c55ac298-d536-4307-90ce-871e8fe1c2f3.png)

**Comment by sunshineatnoon** [comment]
The VGG is from the [WCT](https://arxiv.org/pdf/1705.08086.pdf) algorithm.
