### ISSUE TITLE
RuntimeError for photorealistic style transfer

### ISSUE THREAD

**Issue by EndyWon** [sunshineatnoon/LinearStyleTransfer#2]
HI, when i run the TestPhotoReal.py for photorealistic style transfer, there are RuntimeError,
such as:
RuntimeError: index_copy_(): Source/destination tensor must have same slice shapes. Destination slice shape: [512] at dimension 1 and source slice shape: [843] at dimension 0.

The images i used are your released ones.
How to solve it?

**Comment by sunshineatnoon** [comment]
What's your pytorch version? I ran to the same error when using newer version pytorch (e.g. 1.0), but it should run on 0.4.1.

**Comment by EndyWon** [comment]
Yes, i change my pytorch version to 0.4.1, the problem has been solved. Thanks!
