### ISSUE TITLE
Photorealistic style transfer with segmentation results are all grayish 

### ISSUE THREAD

**Issue by lQingRu** [sunshineatnoon/LinearStyleTransfer#4]
I have tried segmenting a very simple architecture image as seen below:
**(All images are in .jpg format)**

Content image and its segmented image:
![Architecture_3](https://user-images.githubusercontent.com/41319608/66256663-b8b43400-e7c2-11e9-8ef0-29d40d28e535.jpg)
![Architecture_3](https://user-images.githubusercontent.com/41319608/66256680-fdd86600-e7c2-11e9-8c4d-3a96e71ec3ed.jpg)

Style image and its segmented image:
![Architecture_5](https://user-images.githubusercontent.com/41319608/66256702-2eb89b00-e7c3-11e9-829b-b5ddd5d14377.jpg)
![Architecture_5](https://user-images.githubusercontent.com/41319608/66256703-3415e580-e7c3-11e9-8846-ce1afd2de1c3.jpg)

Output:
![Architecture_3_5-3](https://user-images.githubusercontent.com/41319608/66256708-4abc3c80-e7c3-11e9-8c0f-a7836d3d3648.jpg)

All the images I have tried, with relatively similar segmentation classes, received the same output where the image appears to be grayish and blurred.
Could you please explain if there are additional criteria i need to take into consideration when styling images with segmentation? Or any extra parameters I need to tweak?

**Comment by sunshineatnoon** [comment]
I suppose you are trying the photo-realistic style transfer? Could you provide me the images you use and the command you tried?

**Comment by sunshineatnoon** [comment]
Close due to inactivity, please feel free to re-open.
