### ISSUE TITLE
reproduce the results

### ISSUE THREAD

**Issue by CrossLee1** [sunshineatnoon/LinearStyleTransfer#6]
I download the pretrained models and a style image:

![water](https://user-images.githubusercontent.com/18067400/69208221-bc8ef080-0b8d-11ea-813a-352aa799b797.png)

after running the test command `python TestArtistic.py`, I got the following result

![1_water](https://user-images.githubusercontent.com/18067400/69208274-ea743500-0b8d-11ea-96fd-603e704d12ef.png)

The performance is inferior to the release demo. The demo result seems more sharper and more beautiful. Where am I wrong? 

![11](https://user-images.githubusercontent.com/18067400/69208353-4474fa80-0b8e-11ea-9f6e-f22c95384c91.png)

**Comment by sunshineatnoon** [comment]
Hi, all images in the demo are 512x512 images, you can use `python TestArtistic.py --fineSize 512` to get the results. It looks sharper because it is less stylized.

**Comment by CrossLee1** [comment]
Thanks for your timely reply
