### ISSUE TITLE
ModuleNotFoundError: No module named 'torchvision'

### ISSUE THREAD

**Issue by shuuchen** [sunshineatnoon/LinearStyleTransfer#7]
Hi,

I tried to run with torch 0.4.1, but torchvision cannot be found when I run:
```
 python TestPhotoReal.py
```

When I tried to install torchvision, the pytorch is automatically updated to 1.2, which will raise another error:
```
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
```

Did anyone meet similar problems ?

**Comment by sunshineatnoon** [comment]
Hi, could you try to install lower version torchvision so that pytorch would not be automatically updated?

**Comment by sunshineatnoon** [comment]
Close due to lack of feedback. Feel free to reopen the issue.
