### ISSUE TITLE
A tiny question about file 'real-time-demo.py'

### ISSUE THREAD

**Issue by RainbowRui** [sunshineatnoon/LinearStyleTransfer#8]
When I run 'real-time-demo.py', system tells me there is an error: AttributeError: 'Namespace' object has no attribute 'dec_dir'. So I think if we should change the 59th line in file 'real-time-demo.py' to: dec.load_state_dict(torch.load(opt.decoder_dir)). Thanks!

**Comment by sunshineatnoon** [comment]
Yes, I think so. Please let me know if there's any other issues.

**Comment by sunshineatnoon** [comment]
Close for lack of feedback, please feel free to re-open.
